### ISSUE TITLE
Using in windows 7

### ISSUE THREAD

**Issue by llcc** [abo-abo/org-download#10]
Hi, abo-abo,
Thanks for your great org-download.
I am supposed that the codes can be used formally in linux, but when i use it in windows 7, some issues exists:

1. I downloaded the wget that can be used in windows 7, but neither the drag from browser and file explorer nor paste from clipboard can be done. 

2. Then i tried to use the fucntion like `org-download-image` with argument with link in org-mode. The result was that i can not produce any image in my directory. I edebug the function, it seems there is something wrong with the full file name with time-stamp, maybe the eget command-line  also has some problems. 

I am not sure whether it should be working rightly on others' windows, above issues in my windows puzzle me. Thanks in advance for your any help.

**Comment by david-sitsky** [comment]
FWIW.. I got this working under Windows now and have added pull request for it: https://github.com/abo-abo/org-download/pull/22

**Comment by abo-abo** [comment]
Hopefully, this is fixed now. Thanks again, @david-sitsky.

**Comment by david-sitsky** [comment]
No worries - thanks for writing org-download!
