### ISSUE TITLE
Why bmp when in window system?

### ISSUE THREAD

**Issue by tumashu** [abo-abo/org-download#101]
I use emacs26+msys2 in window7, when I drag a jpg or png link from firefox to emacs with the help of org-download,  a bmp file link will be inserted into org buffer, how to create jpg/png link instead?

**Comment by tumashu** [comment]
```
#+DOWNLOADED: file:C%3A/Users/feng/AppData/Local/Temp/z7h39mzb.bmp @ 2019-05-24 17:41:21
[[file:data/e7/d0a742-949c-4bb8-b91b-edc2b8e05156/z7h39mzb_2019-05-24_17-41-21.bmp]]

```

**Comment by abo-abo** [comment]
No idea why this should happen. We use this code:

    (url-path-and-query (url-generic-parse-url link))

So this is likely a bug in those built-in functions. Can you check?

**Comment by tumashu** [comment]
I find that firefox has this problem, ie has no this problem.
