### ISSUE TITLE
Take screenshot and save to clipboard using imagemagick import and xclip

### ISSUE THREAD

**Issue by codygman** [abo-abo/org-download#108]
This is some issue with xsel and xclip hanging I think.

```
(setq org-download-screenshot-method "import png:- | xsel --clipboard --input && xclip --clipboard --output > %s")
```

The use case is I typically want to insert screenshots into org mode, but about every 5th one I'll want to copy the screenshot to my clipboard as well to upload it somewhere. My solution is just making the default copy the image to my clipboard buffer and have a clipboard history manager.

The problem is that writing to file seems to make things hang?

This minimal elisp demonstrates the issue:

```
(shell-command "xclip -selection clipboard -target image/png -filter < /tmp/filename > /dev/null")
```

Even though in `M-x shell` this works fine:

```
bash -c "xclip -selection clipboard -target image/png -filter < /tmp/filename > /dev/null; echo $?"
```

**Comment by codygman** [comment]
I posted for help on reddit and was given a solution for the redirection hanging issue. The key seemed to be `&>` instead of `>`. The full solution is:

```
(setq org-download-screenshot-method "export filename=\"%s\"; import png:\"$filename\" ;xclip -selection clipboard -target image/png -filter < \"$filename\" &>/dev/null")
```

**Comment by abo-abo** [comment]
Can we close this then?

**Comment by codygman** [comment]
Sure! Sorry, I wasn't sure if you thought this was worth extending into a feature.

**Comment by abo-abo** [comment]
> this was worth extending into a feature

Thanks, it's a good idea to document this method. Now the users can discover it via <kbd>M-x</kbd> `customize`.
