### ISSUE TITLE
Remove or modify downloaded tag for screenshots

### ISSUE THREAD

**Issue by ariekahn** [abo-abo/org-download#109]
The DOWNLOADED attribute adds unnecessary clutter with screenshots. At least on Mac OS using `screencapture`, I end up with something like
```
#+DOWNLOADED: /var/folders/q0/t3yx0cwx59n_fwfy779msmxm0000gn/T/screenshot.png @ 2019-10-14 14:55:54
```

Clearly recording a temporary file path isn't very useful. Maybe it would be better to just indicate it was a screenshot? Something like

```
#+DOWNLOADED: screenshot @ 2019-10-14 14:55:54
```

**Comment by abo-abo** [comment]
Thanks.
