### ISSUE TITLE
if: Wrong type argument: number-or-marker-p, nil with org-download-yank

### ISSUE THREAD

**Issue by abo-abo** [abo-abo/org-download#11]

**Comment by loochao** [comment]
Hi, let's continue the discussion here, is there anything else I could do to test? Also, just a quick idea is that maybe org-download could also support other format like pdf, so org could be turned into an collector?

**Comment by abo-abo** [comment]
Hi. First of all, are you using the most current github version?

> Also, just a quick idea is that maybe org-download could also support other format like pdf, so org could be turned into an collector?

This can be done in a more elegant way, see
e.g. https://github.com/abo-abo/org-fu for the capture of pdf
documents from `doc-view` or `dired`.

**Comment by loochao** [comment]
I believe it's the latest version, for what I did is restart emacs,  copy the raw file content of org-download to my *scratch* and eval-buffer, (require 'org-download), then create a buffer named "test.org", drag an image into the buffer to see if the image shows up or not.

-- Checking out org-fu. thanks for the information!

**Comment by abo-abo** [comment]
OK, try to do this:

1. eval with <kbd>C-x C-e</kbd> this: `(kill-new  "https://www.google.nl/images/srpr/logo11w.png")`, it will copy a known good image link to your kill ring.
2. M-x `toggle-debug-on-error`. It should say: "Debug on Error enabled globally".
3. Move to an `org-mode` buffer and call `org-download-yank`. Post the full error thing here.

**Comment by loochao** [comment]
Eh... After following the instruction, no error... (by checking the *Message* buffer), also nothing happened... no image downloaded or showed up in the org-mode buffer...

**Comment by abo-abo** [comment]
Can you check again that this works, with the current code:

    (defun org-download-yank-1 ()
      (interactive)
      (let ((filename "./foo.png"))
        (org-download--image
         "https://www.google.nl/images/srpr/logo11w.png"
         filename)
        (insert (format "[[%s]]" filename))
        (org-display-inline-images)))

**Comment by loochao** [comment]
This one works! And also, org-download-yank also works now... Maybe my last test has something wrong? And I disabled the global evil-minor-mode as well.

**Comment by loochao** [comment]
(kill-new "https://www.google.nl/images/srpr/logo11w.png") + org-download-yank will put the google logo into my org buffer, but dragging still gives a link only.

org-download-yank-1 also works.

**Comment by abo-abo** [comment]
OK, so now, at least the package is usable, just not very convenient.

Now, evaluate this code, and try the drag-and-drop:

    (defun org-download-dnd (uri action)
      "When in `org-mode' and URI points to image, download it.
    Otherwise, pass URI and ACTION back to dnd dispatch."
      (message "org-dnd was called!")
      (if (eq major-mode 'org-mode)
          ;; probably shouldn't redirect
          (unless (org-download-image uri)
            (message "not an image URL"))
        ;; redirect to someone else
        (let ((dnd-protocol-alist
               (rassq-delete-all
                'org-download-dnd
                (copy-alist dnd-protocol-alist))))
          (dnd-handle-one-url nil action uri))))

Tell me if you get "org-dnd was called!" message or not.

**Comment by abo-abo** [comment]
You have to evaluate this function with <kbd>C-M-x</kbd> (`eval-defun`).

**Comment by loochao** [comment]
No... By dragging there's still only links and no "org-dnd was called" message...

**Comment by abo-abo** [comment]
What's your Emacs version and `dnd-protocol-alist`?

**Comment by loochao** [comment]
GNU Emacs 24.3.1 (x86_64-apple-darwin, NS apple-appkit-1038.36) of 2013-03-13 on bob.porkrind.org
====
dnd-protocol-alist:

Value:
 (("^\\(https?\\|ftp\\|file\\|nfs\\)://" . org-download-dnd)
 ("^file:///" . dnd-open-local-file)
 ("^file://" . dnd-open-file)
 ("^file:" . dnd-open-local-file)
 ("^\\(https?\\|ftp\\|file\\|nfs\\)://" . dnd-open-file))

Original value was 
(("^file:///" . dnd-open-local-file)
 ("^file://" . dnd-open-file)
 ("^file:" . dnd-open-local-file)
 ("^\\(https?\\|ftp\\|file\\|nfs\\)://" . dnd-open-file))

**Comment by abo-abo** [comment]
It seems that it's wrong, the paren before `https` should be double escaped.
Try this:

    (setq dnd-protocol-alist
          '(("^\\(https?\\|ftp\\|file\\|nfs\\)://" . org-download-dnd)
           ("^file:///" . dnd-open-local-file)
           ("^file://" . dnd-open-file)
           ("^file:" . dnd-open-local-file)
           ("^\\(https?\\|ftp\\|file\\|nfs\\)://" . dnd-open-file)))

**Comment by loochao** [comment]
Tried, still doesn't not work. Dragging and drop gives only the link...

**Comment by abo-abo** [comment]
What do you mean by that?

**Comment by loochao** [comment]
By eval
(setq dnd-protocol-alist
      '(("^\\(https?\\|ftp\\|file\\|nfs\\)://" . org-download-dnd)
       ("^file:///" . dnd-open-local-file)
       ("^file://" . dnd-open-file)
       ("^file:" . dnd-open-local-file)
       ("^\\(https?\\|ftp\\|file\\|nfs\\)://" . dnd-open-file)))
then tried drag-and-drop into org-mode buffer still gives the link...

I guess it's the problem of dnd?

**Comment by abo-abo** [comment]
Again, the paren before `https` isn't double-escaped. How is this happening?

**Comment by loochao** [comment]
(setq dnd-protocol-alist
      '(("^\\(https?\\|ftp\\|file\\|nfs\\)://" . org-download-dnd)
       ("^file:///" . dnd-open-local-file)
       ("^file://" . dnd-open-file)
       ("^file:" . dnd-open-local-file)
       ("^\\(https?\\|ftp\\|file\\|nfs\\)://" . dnd-open-file)))

**Comment by loochao** [comment]
Oh, I just realized it's github editor will automatically make \\ -> \, in my system it was \\ ...

**Comment by loochao** [comment]
I finally make sure it's the Emacs version which plays the role.

I downloaded a newer version of the Mac Emacs, and org-download works there. The working Emacs is the current version of Mac OSX GNU Emacs, from http://emacsformacosx.com/ (24.4.1 (x86_64-apple-darwin12.5.0, NS apple-appkit-1187.40) of 2014-10-20 on builder10-8.porkrind.org)

While it won't work with exactly the same setting on a previous version of Emacs, downloaded earlier from the same website, whose version is GNU Emacs 24.3.1 (x86_64-apple-darwin, NS apple-appkit-1038.36) of 2013-03-13 on bob.porkrind.org.

The value of dnd-protocol-alist when org-download is working is:
----
(("^\\\\(https?\\\\|ftp\\\\|file\\\\|nfs\\)://" . org-download-dnd)
 ("^file:///" . dnd-open-local-file)
 ("^file://" . dnd-open-file)
 ("^file:" . dnd-open-local-file)
 ("^\\(https?\\|ftp\\|file\\|nfs\\)://" . dnd-open-file))
----
Of course, after eval (setq dnd-protocol-alist '((".*" . org-download-dnd))), org-download will still function, as tested.

**Comment by abo-abo** [comment]
Thanks!
