### ISSUE TITLE
Option to prepend org-download-timestamp instead

### ISSUE THREAD

**Issue by jackbaty** [abo-abo/org-download#110]
I would prefer that `org-download-timestamp` was _prepended_ to the filename rather than appended. (e.g. `2019-10-15-myfile.jpg`) I cheated and simply swapped lines 78 and 79 in a local copy but ideally it could be configured somehow. (`org-download-timestamp-method 'prepend` or similar)

**Comment by abo-abo** [comment]
You can customize it like this:

```elisp
(setq org-download-annotate-function
      (lambda (link)
        (when (equal link org-download-screenshot-file)
          (setq link "screenshot"))
        (format "#+DOWNLOADED: @ %s from %s\n"
                (format-time-string "%Y-%m-%d %H:%M:%S")
                link)))
```

**Comment by jackbaty** [comment]
Thanks for following up. Forgive me, but I'm not sure how the recommended customization will do what I'm thinking of here. I'm new enough to lisp that you should assume I'm an idiot here. (Note that I'm not using the screenshot functionality at all.)

I have `org-download-image-dir` set to "./img" and `org-download-timestamp` set to "-%Y-%m-%d"

Currently, if I drag and drop the file "myfile.jpg" from the Finder (macOS), it gets put into my `org-download-image-dir` as "./img/myfile-2019-10-15.jpg". This is what I would expect.

What I'd like is for the name to end up being "./img/2019-10-15-myfile.jpg" instead.

To do this, I changed `org-download-timestamp` to "%Y-%m-%d-" (trailing hyphen) and switched 2 lines in `org-download--fullname-format`. Like so...

``` emacs-lisp
(defun org-download--fullname-format (filename &optional ext)
  "It's affected by `org-download-timestamp'.
EXT can hold the file extension, in case FILENAME doesn't provide it."
  (format "%s%s.%s"
          (format-time-string org-download-timestamp)  ; <--- Swapped this
	  (file-name-sans-extension filename)          ; <--- and this
          (or ext (file-name-extension filename))))
```

(The line numbers referenced in my original note should have been 278 and 279, sorry).

I don't understand how to change this behavior based on the snippet you provided.

**Comment by abo-abo** [comment]
Thanks, please test. I've actually changed the defaults to start with a timestamp, since then the directory listing becomes more useful.

**Comment by jackbaty** [comment]
This works perfectly, thank you!
