### ISSUE TITLE
File path in org adds the .attach directory which does not match the image file path.

### ISSUE THREAD

**Issue by edlew1s** [abo-abo/org-download#117]
As the title suggests, when I drag an image into org or take a screenshot, the file is placed into my specified directory however the file path in org has an added .attach directory in it.

I have set up org-download with the following:
```
(require 'org-download)
(add-hook 'dired-mode-hook 'org-download-enable)
(setq org-download-method 'directory)
(setq-default org-download-image-dir "./img")
```
The file path becomes ~/Documents/Notes/.attach/img/... instead of ~/Documents/Notes/img/... where the image is stored.

What would you recommend?

**Comment by abo-abo** [comment]
Sorry, can't reproduce. Please try to reproduce it with `emacs -Q`, then loading `org-download`.

**Comment by edlew1s** [comment]
I installed manually through emacs -Q and cannot reproduce the error either. I am using Doom as my emacs config so maybe there is a conflict going on there?

**Comment by phi-go** [comment]
So I had the same problem and the thing is that this config conflicts with the :lang / org / +dragndrop module from doom emacs. They also include and configure org-download there, which causes the problems.

If you are happy with the doom dragndrop functionality you should already be set.
However, if you want to configure this package yourself you should disable the dragndrop module and configure things yourself.

**Comment by edlew1s** [comment]
> So I had the same problem and the thing is that this config conflicts with the :lang / org / +dragndrop module from doom emacs. They also include and configure org-download there, which causes the problems.
> 
> If you are happy with the doom dragndrop functionality you should already be set.
> However, if you want to configure this package yourself you should disable the dragndrop module and configure things yourself.

This has fixed my issue, thankyou! I shall close the issue.
