### ISSUE TITLE
org-download-image doesn't work when org heading has empty title

### ISSUE THREAD

**Issue by tmalsburg** [abo-abo/org-download#120]
Headings can have empty titles in org, example:

```
* 
This is a section with empty header.
```

When I try to `org-download-image` in this section, I get

```
Wrong type argument: arrayp, nil

```

Reason is that `org-heading-components` has `nil` in position 4 instead of the title string when called in function `org-download-get-heading`.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by tmalsburg** [comment]
Seems to work.  Thank you!
