### ISSUE TITLE
Images are not inserted

### ISSUE THREAD

**Issue by AyeGill** [abo-abo/org-download#121]
Hi, I'm trying to get the package to work, but whether I try to take a screenshot or drag an image, not links are inserted into my org files.

Running `org-download-screenshot` does run `scrot`, but the screenshots are just dumped into the current directory, nothing is inserted in the org file.
And dragging an image from my browser onto the org buffer does apparently nothing.
Here is a fragment of my configuration (I am using doom emacs):

(The folders `~/org/img/` and `~/tmp/` both exist, if that matters)

```
(use-package! org-download
  :after org
  :custom
  (org-download-image-dir "~/org/img/")
  (org-download-screenshot-method "scrot -s %s")
  (org-download-method 'directory)
  (org-download-screenshot-file "~/tmp/screenshot.png")
  (org-download-heading-lvl 1))
```

**Comment by abo-abo** [comment]
What's your system?

Can you test it like this:

```sh
git clone https://github.com/abo-abo/org-download/
cd org-download && make emacsq
```

**Comment by AyeGill** [comment]
It opens an empty emacs frame and displays the text "Cannot open load file: No such file or directory, async" in the minibuffer.

![image](https://user-images.githubusercontent.com/2692879/78989826-007e9400-7b35-11ea-94f1-3fa2854f865d.png)

**Comment by abo-abo** [comment]
Oh sorry. You need to do:

```sh
make update
make emacsq
```

**Comment by AyeGill** [comment]
Thanks - `org-download-screenshot` works in the test window

**Comment by abo-abo** [comment]
OK. I can close the issue then.
