### ISSUE TITLE
filename/screenshot:replace empty spaces,save as timestamp_buffername_current heading name

### ISSUE THREAD

**Issue by MorphicResonance** [abo-abo/org-download#124]
I'm trying to configure file/screenshot downloading with the most informative name which will be created automatically.
So for the screenshot it can be timestamp_current-buffer-name_current-org-heading-name.extension . One snippet came close to this from Jethro Kuan:
```
(defun +org/org-download-method (link)
    (let ((filename
           (file-name-nondirectory
            (car (url-path-and-query
                  (url-generic-parse-url link)))))
          ;; Create folder name with current buffer name, and place in root dir
          (dirname (concat "./images/"
                           (replace-regexp-in-string " " "_"
                                    (downcase (file-name-base buffer-file-name)))))
          (filename-with-timestamp (format "%s%s.%s"
                                     (file-name-sans-extension filename)
                                     (format-time-string org-download-timestamp)
                                      (file-name-extension filename))))
      (make-directory dirname t)
      (expand-file-name filename-with-timestamp dirname)))
```
Good thing that it replace spaces from filenames. But the problem that It does work in other direction , creates folders for each org file you operate.
Please modify this code that it will able to save file/ screenshot with timestamp+current buffer name+current heading name(if exist) in the folder where org file is located.
So it will be the most informative screenshot name that org-download can create automatically.

**Comment by abo-abo** [comment]
It looks like you're trying to write down a custom `org-download-method`. I don't think it's useful enough to be included into org-download.el by default.

If you have questions about Emacs config, I suggest https://emacs.stackexchange.com/.

**Comment by MorphicResonance** [comment]
It should not be included by default expect maybe white space replacement. My query combines several of the repeated problems here for users with file names. It would be nice to have such combined code for emacs, if possible.

**Comment by ugurbolat** [comment]
I would also appreciate it if the spaces were handled like discussed above...
