### ISSUE TITLE
File URI parsed incorrectly, extension duplicates for non-images on macOS with certain Emacs builds

### ISSUE THREAD

**Issue by freetonik** [abo-abo/org-download#126]
Hi Oleh,
thank you for org-download!

When using [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus) on macOS, drag-n-dropping files from local filesystem results in URI's with pattern of `file:/bla/a.pdf`, not `file:///bla/a.pdf`. As a result, when `org-download--parse-link` is called, `(string-match "^file:///" link)` condition does not evaluate to true, which then forces org-download to detect and append an extension, and the resulting file is saved with 2 extensions (e.g. `a.pdf` becomes `a.pdf.pdf`).

According to [RFC 8089](https://tools.ietf.org/html/rfc8089), both one-slash and three-slash URIs are valid:

```
The minimal representation of a local file with no authority field
and an absolute path that begins with a slash "/".  For example:

*  "file:/path/to/file"
```

Not sure how best to handle this, but perhaps `(string-match "^file:///" link)` should be `(string-match "^file:/" link)`?

Cheers!

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by freetonik** [comment]
Works great, thank you!
