### ISSUE TITLE
Absolute path to the image

### ISSUE THREAD

**Issue by rsuhada** [abo-abo/org-download#128]
`org-download` inserts links with a relative path to the image. Is there a way to force the absolute path as it seems to me more robust (and shorter for deeply nested org files)?

Example: 
I have set my org-download-image dir:
`(setq-default org-download-image-dir "~/documents_lib/org-image-archive")`

This is an example output:
`
#+DOWNLOADED: https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg @ 2020-06-17 20:15:45]

[[file:../../../../../documents_lib/org-image-archive/questions_to_taylor/2020-06-17_20-15-45_EmacsIcon.svg]]
`

I'd prefer the absolute path:
`
#+DOWNLOADED: https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg @ 2020-06-17 20:15:45

[[file:~/documents_lib/org-image-archive/questions_to_taylor/2020-06-17_20-15-45_EmacsIcon.svg]]
`
Is this possible?

**Comment by tmccartney** [comment]
Try adding this to your config:

`(setq-default org-download-abbreviate-filename-function 'expand-file-name)`

Note - I haven't tested it.

**Comment by tmccartney** [comment]
Duplicate of #88

**Comment by rsuhada** [comment]
Thanks, it works!

(I did search in issues but somehow managed to miss #88, sorry)

**Comment by hkienle** [comment]
Just for the record, if you prefer `~/` instead of an absolute path like `/home/myuserdir/` then this does the trick:
`(setq org-download-abbreviate-filename-function 'abbreviate-file-name)`

Reference: https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Names.html#index-abbreviate_002dfile_002dname
