### ISSUE TITLE
Drag images from the chrome seems don't work

### ISSUE THREAD

**Issue by qinshulei** [abo-abo/org-download#13]
Hi abo-abo,

  I try to drag image from the chrome to org-mode.But it didn't work. It works fine with firefox.

  Is it only support firefox currently?

**Comment by abo-abo** [comment]
This seems like a bug in the DND, which is part of Emacs. The link never gets through to `org-download` code when dragging from Chromium. Do you have time to report the bug, or should I do it?

**Comment by abo-abo** [comment]
Bug reported at http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19885.

**Comment by abo-abo** [comment]
It's a bug in Chromium, since it doesn't follow the
[xdnd standard](http://www.newplanetsoftware.com/xdnd/).

I've raised a [Chromium bug](https://code.google.com/p/chromium/issues/detail?id=461390).
If they ever fix it, `org-download` will automatically start to work.

**Comment by qinshulei** [comment]
Thank you.
