### ISSUE TITLE
Global variable options

### ISSUE THREAD

**Issue by mankoff** [abo-abo/org-download#14]
I'd always like to have images stored in a global folder, not in sub-folders of the current Org file. Is there a way to set variables globally? Should this be done by adding `(add-hook 'org-mode-hook)`?

**Comment by abo-abo** [comment]
You can already set `org-download-image-dir`.

It's also possible to set the global folder on a per-file basis (it's
documented at the start of org-download.el):

    # -*- mode: Org; org-download-image-dir: "~/Pictures/foo"; -*-

**Comment by mankoff** [comment]
But doing something "global" on a "per file basis" sort-of defeats the purpose of global, or at least re-defines the meaning of global.

**Comment by abo-abo** [comment]
It doesn't. You can set it for all files. Then you can override it for a particular file if you want.
Or not.

**Comment by mankoff** [comment]
I can set it for al files *in each file* via the method you showed above. Is it possible to set it for all files once in my init file? The help for `org-download-image-dir` says `Automatically becomes buffer-local when set.`. 

Sorry if I'm confused here. I've set it in my init.org file. When I open a different Org file, it is not set. To me that means it isn't global.

**Comment by abo-abo** [comment]
I think you're looking for:

    (setq-default org-download-image-dir "~/Pictures/")

**Comment by mankoff** [comment]
Yes. Thank you! Sorry for the confusion.

**Comment by abo-abo** [comment]
No problem. `setq-default` is a standard approach for buffer-local variables. You can use it
for other packages as well.
