### ISSUE TITLE
Downloads with spaces in filename result in filenames with encoding.

### ISSUE THREAD

**Issue by andreaswittmann** [abo-abo/org-download#142]
A similar problem was discussed and handled in  https://github.com/abo-abo/org-download/issues/83
If a file that contains a filename with spaces is dragged to an org file, the uri in org-download-dnd is modified to contain %20 instead of " ".
While Emacs org-mode and Linux can handle the resulting links, problems occur with org-publish to HTML. The resulting link cannot be opened from the website, because
the browser interprets string %20. It replaces it with " " which leads to a "File not found" error. 
Proposal:  Replace all %20 with " " in the constructed link in org-download-image.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by andreaswittmann** [comment]
This works for me. Thanks.
