### ISSUE TITLE
How can I resize a screenshot image?

### ISSUE THREAD

**Issue by friedgreenrepos** [abo-abo/org-download#169]
Is there a way to resize an image capture via org-download-screenshot?

**Comment by friedgreenrepos** [comment]
`#+attr_latex: :width 150px` after the `#+DOWNLOADED: screenshot @...` line seem to work.

**Comment by danielkrajnik** [comment]
I seem to have the same problem and can't figure out what's wrong with this. Images get cropped, `#+attr_org:` don't work, links get pasted as `download: ...`  instead of `file:...``  
![image](https://github.com/abo-abo/org-download/assets/15096799/94340e77-e656-4f0b-9afa-06cc8467e2b5)
