### ISSUE TITLE
global setting: org-download-image-dir

### ISSUE THREAD

**Issue by yitang** [abo-abo/org-download#17]
Hi,

I think org-download is a brilliant idea, I'd like to use it in drafting reports. I just wonder if I can set `org-download-image-dir` as a global variable, to `img/` folder, which is relative path to the B point (the target buffer)? 

I've tried to use 

`-*- mode: Org; org-download-image-dir: ~/Pictures/foo; -*- `

as shown in README.me, but it doesn't works. 

-Yi

**Comment by abo-abo** [comment]
What you used can set the variable for the current file.
To set it globally, use this:

```elisp
(setq-default org-download-image-dir "~/Pictures/foo")
```

**Comment by yitang** [comment]
it works, thanks!

**Comment by abo-abo** [comment]
Alright, you're welcome.
