### ISSUE TITLE
change org-download-heading-lvl to buffer-name? 

### ISSUE THREAD

**Issue by yitang** [abo-abo/org-download#19]
Hi,

I separate projects by different .org files, so I have `PorjectA.org` and `ProjectB.org`, and is it possible to associate the file name of the screenshot to buffer name? then I will have 

````
/img/ProjectA/xxxx.png
/img/ProjectB/xxxx.png
```

which makes it is easier to manage and more robust to the headlines as we potentially change it. 

-Yi

**Comment by abo-abo** [comment]
You can just leave `org-download-heading-lvl` at nil and
use this in Project A:

    -*- mode: Org; org-download-image-dir: /img/ProjectA; -*-

and this in Project B:

    -*- mode: Org; org-download-image-dir: /img/ProjectB; -*-

**Comment by yitang** [comment]
great, I will use 

`(setq-default org-download-heading-lvl nil)` 

as default. 

and 

`-*- mode: Org; org-download-image-dir: "/img/ProjectA"; -*-`

for different files. 

Note I need to quote in my machine. 

Thank you very much.

**Comment by abo-abo** [comment]
> Note I need to quote in my machine.

Yes, that's an error on my part. It should be quoted everywhere. Thanks for noticing.
