### ISSUE TITLE
dnd does not work in OS X

### ISSUE THREAD

**Issue by brabalan** [abo-abo/org-download#20]
I'm trying org-download and I have `org-download-yank` working. Unfortunately drag and drop does not work for images, I just get a url inserted.

I'm using this emacs: https://github.com/railwaycat/homebrew-emacsmacport/releases

_Edit_: I tried dnd of images from the local file system and it works. It seems the issue comes from images from Firefox.

**Comment by abo-abo** [comment]
> I just get a url inserted.

Can you give more details, please? I don't have OSX, so I'd be fixing the bug blind, but if the URL inserted is the correct one, maybe something can be done.

**Comment by brabalan** [comment]
It depends: if it's a pure image, then it's the correct url (pointing to the image file online). If the image is also a link, then it's the url of the link that is inserted. Is there a way for me to see what information emacs get when I do the drop?

**Comment by abo-abo** [comment]
> Is there a way for me to see what information emacs get when I do the drop?

Sorry for the late reply. You can get it by re-defining this function:

```elisp
(defun org-download-dnd (uri action)
  "When in `org-mode' and URI points to image, download it.
Otherwise, pass URI and ACTION back to dnd dispatch."
  (message "URI: %S\nACTION: %S" uri action))
```

**Comment by xsy233** [comment]
same problem on osx (using spacemacs with emacs-mac-port)
local file or directly using org-download-image command both worked

however, when I drap and drop an image from chrome, org-download-dnd is never called,
the image is displayed in the buffer, but saving the buffer will clear it. 
In safari, the href of the image is inserted.

**Comment by abo-abo** [comment]
The Chrome issue is due to a bug in Chrome. It was reported but not yet fixed.

**Comment by stardiviner** [comment]
Not work in Arch Linux too, I tried to drag image from KDE files manager "Dolphin" and from Chrome. Both does not work. And Emacs show output in minibuffer with `5 1`.

**Comment by paulelms** [comment]
I have everything works out of the box with macOS Sierra, Safari 10.1 and emacs 25.1.1 + spacemacs.
Emacs build:
brew tap d12frosted/emacs-plus
brew install emacs-plus && brew linkapps

**Comment by brabalan** [comment]
I think this is an emacs-mac specific bug. In my case org-download-dnd is never called.

**Comment by brabalan** [comment]
Good news: it seems that this will be fixed in the next version of emacs-mac.
https://lists.gnu.org/archive/html/emacs-devel/2017-02/msg00125.html

**Comment by abo-abo** [comment]
@brabalan Good to hear, can you specify the version in the comments? Maybe someone can confirm that the fix works.

**Comment by brabalan** [comment]
I confirm this is working with emacs-mac 25.2.
