### ISSUE TITLE
What is `#+DOWNLOADED:` for?

### ISSUE THREAD

**Issue by buhtzz** [abo-abo/org-download#205]
I created this two lines in an org roam file via your great package.

```
#+DOWNLOADED: https://training.cochrane.org/sites/training.cochrane.org/files/public/uploads/handbook/chapter-06_files/image011.png @ 2022-08-03 14:53:41
[[file:2022-08-03_14-53-40_image011.png]]
```

When exporting this to HTML via `org-html-export-as-html` the first line has no effect and is ignored. The resulting HTML looks like this

```
<div id="orgae4648a" class="figure">
<p><img src="2022-08-03_14-53-40_image011.png" alt="2022-08-03_14-53-40_image011.png" />
</p>
</div>
```
I would assume that the first org line would result in something like an image caption or an tooltip description when rendered as HTML. What is the intention of that first org line starting with `#+DOWNLOADED:`?

**Comment by abo-abo** [comment]
The intention of `#+DOWNLOADED:` was only to document where the image came from. It might be useful in the far future to know the source of the image.

It's a nice idea to use that info as a figure caption, but I think Org has already a mechanism for figure captions.
It's possible to write a simple code that translates `#+DOWNLOADED:` into figure captions if needed. But I don't think it should be added here probably.

**Comment by buhtzz** [comment]
Thanks for your explanation. I needed to know to let my [hyperorg](https://codeberg.org/buhtz/hyperorg) interpret that correct. Hyperorg does translate things like that to HTML.
