### ISSUE TITLE
org-download stoped downloading to user defined dir

### ISSUE THREAD

**Issue by zeltak** [abo-abo/org-download#21]
Hi!

i suddenly realised org-download has stoped downloading images to user defined dir

i have this setting

 (use-package org-download 
   :ensure t
   :config
   (setq-default org-download-heading-lvl nil)
   (setq-default org-download-image-dir "/home/zeltak/Sync/attach/images_2015")
  )

it dosent seem like its downloading to /home/zeltak/Sync/attach/images_2015

any settings changed recently?

best

Z

**Comment by abo-abo** [comment]
> any settings changed recently?

No, it's the same that it was before. Your settings look OK. Try to restart/upgrade Emacs.

**Comment by zeltak** [comment]
ha, removing org-download and reinstalling did the trick :)

thx again

Itai

**Comment by zeltak** [comment]
Hi again

so some more updates and org-download image drag is broken again. i tried again uninstalling with no success. any idea?

thx!

Z

**Comment by abo-abo** [comment]
Still works fine in my Emacs. Did you change your Emacs version or system? See if `org-download-yank` at least works.

**Comment by zeltak** [comment]
mm funny thing i updated org-mode (and contrib) and it seems to work now..weird :)

**Comment by abo-abo** [comment]
Closing for now, hopefully it still works.
