### ISSUE TITLE
folder structure

### ISSUE THREAD

**Issue by dlebrecht** [abo-abo/org-download#23]
im not a lisp programmer (yet), thus for the time being i will just request a feature

i've been using org-download almost daily for the past 2 months.  one thing that is a bit distrubing is that the foldername inherits the heading in its current state with its current tags. 

for example, i had such a headline that created the following foldername:
"progress report"

but at some point i made it a todo and tagged it, and thus when i use org-download i get a new folder: 

"TODO progress report                        :anthony:ustim:meeting:"

it would be good if your code could parse out only the heading itself from the plain text. 

i frequently have issues exporting to latex after using org-download, because of the crazy foldernames i end up with.

alternatively, i noticed some other extensions, like org-mobile, that makes use of ID property. For example, below the headings, i have this as unique identifier for my heading.
:PROPERTIES:
:ID:       3a7884b2-24b9-4035-8280-d018782bd4cd
:END:

**Comment by abo-abo** [comment]
Thanks, please test. There's also `(setq org-download-method 'attach)`, maybe that would work better for you.

**Comment by dlebrecht** [comment]
thanks for the prompt fix. it works as expected on my tests. however setting org-download method to attach is indeed a better option for me.
