### ISSUE TITLE
2 small questions

### ISSUE THREAD

**Issue by zeltak** [abo-abo/org-download#25]
Hi again, how are you?

i have 2 small questions that i can seem to solve

1. i want to get rid of the 
#+DOWNLOADED: /tmp/screenshot.png @ 2015-10-19 09:45:28

line. i tried using this in my config with no success:

(setq-default  org-download-timestamp "")

is this the correct way to get rid of the #+DOWNLOADED line?

2. i cant seem to get local buffer image dirs to work properly
i have this on the top of the file
-*- mode: Org; org-download-image-dir: "~/ZH_tmp/"; org-download-heading-lvl: nil; -*-

but each time i take a screenshot using org-download i get an error:

org-download--image: File already exists: /home/zeltak/ZH_tmp/screenshot.png

any clue?

thx so much!

z

**Comment by abo-abo** [comment]
> (setq-default org-download-timestamp "")

This applies a time stamp to the file name. This is useful in two ways: gives info on download time, separate from the Org document; and serves to make the file name unique.  The second thing will also solve your screenshot problem.

If you don't want the `#+DOWNLOADED:` annotation in your Org document, use this setting:

```elisp
(setq org-download-annotate-function (lambda (_) ""))
```

I suggest that you keep the default value of `org-download-timestamp`. Otherwise, the only thing I can do is generate `screenshot-1.png`, `screenshot-2.png`.  This isn't a better approach than adding time stamps.

**Comment by zeltak** [comment]
Hi

sorry to open this again but i can seem to get rid of the #+DOWNLOADED: annotation
i have this config
````
  (use-package org-download 
   :ensure t
   :config
   (setq-default org-download-heading-lvl nil)
   ;;; to get rid of the #+DOWNLOADED part
   (setq-default org-download-image-dir "/home/zeltak/Sync/attach/images_2015")
   (setq org-download-annotate-function (lambda (_) ""))
  )
```

yet i still get the annotation when i grab an image via screenshot (org-download-screenshot)
Also i notcied that it dosent show the source URL but always a /tmp:

```
#+DOWNLOADED: /tmp/screenshot.png @ 2015-10-25 13:39:20
#+attr_html: :width 300px
[[~/org/attach/bgu/courses/BGU.R/images/screenshot_2015-10-25_13-39-20.png]]
```
can it show the URL it downloaded from?

best

z

**Comment by abo-abo** [comment]
> yet i still get the annotation when i grab an image via screenshot (org-download-screenshot)
> Also i notcied that it dosent show the source URL but always a /tmp:

You should only get this:

    [[~/org/attach/bgu/courses/BGU.R/images/screenshot_2015-10-25_13-39-20.png]]

Try updating the code and restarting Emacs.

> can it show the URL it downloaded from?

It can't, you just turned URL off with this setting:

    (setq org-download-annotate-function (lambda (_) ""))

**Comment by zeltak** [comment]
Hi again

sorry again for the late response (...again so swamped with work thesedays..:( )

so i think i understand things better now. and this line is perfect for me
(setq org-download-annotate-function (lambda (_) ""))

the only issue now is that i cant use org-download-delete anymore since i only have the #+attr_html: :width 600px line now. can org-download-delete be used with the attr line? it dosent seem to work here?

thx
z
