### ISSUE TITLE
can't download image when the link does not point to image type

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/org-download#26]
I have a link want to download as an image.
https://camo.githubusercontent.com/58ab829b38ca08c1ea0a92b647b3a77eedbc04fb/687474703a2f2f64636a6f6e65732e6769746875622e636f6d2f476164666c792e6a6c2f726f636b696e67686f727365666c792e706e67

But org-download can't download it.
I hope org-download can support this, detect it, and rename the result file.

**Comment by abo-abo** [comment]
Thanks.

**Comment by stardiviner** [comment]
Really fast, thanks very much.
