### ISSUE TITLE
[REQUEST] open org-downlaod image in image-editor of choice, then update image in buffer

### ISSUE THREAD

**Issue by zeltak** [abo-abo/org-download#28]
Hi again

so as you know i use org-download daily as one of my main work drivers :)

many times i have a need to quick edit an image in the org buffer which i have downloaded via org-download. for example add a highlight, a red frame etc to highlight stuff on the image for my students.

i know that org-download keeps track of each image (since i can launch org-download-delete).
i was wondering if we can do the same to edit a image from within org, that is:
launch the image in an editor of choice (maybe use a command like org-download-edit?), edit the image there, save,quit and then the new edited image appears in the org buffer :)
i dont know how technically difficult that would be but i did do some stuff like that in the past with very simple bash scripts..though i cant code for shit as you know :)

thanks so much for everything as always

kind regards

Z

**Comment by abo-abo** [comment]
It's not really org-download specific - feeding an org link to a command. But here you go.

**Comment by zeltak** [comment]
Hi again

sorry for the late response in testing but had a crazy week :)

i updated from melpa but i dont see the new commands in the M-x menu. am i missing something? do i need to add config options to get the org-download-edit command?

thx alot!

z
