### ISSUE TITLE
[RE-OPEN] open org-downlaod image in image-editor of choice, then update image in buffer

### ISSUE THREAD

**Issue by zeltak** [abo-abo/org-download#29]
Hi again

sorry for the late response in testing but had a crazy week :) also sorry for reopening the issue in a new ticket but couldn't find a way to re-open last one.

i updated from melpa but i dont see the new commands in the M-x menu. am i missing something? do i need to add config options to get the org-download-edit command?

thx alot!

z

**Comment by abo-abo** [comment]
It's in MELPA. You're probably just using the one from `org-contrib`. Reload the one from `elpa/` and it will work.
