### ISSUE TITLE
org-download-edit open file error

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/org-download#32]
I got this error in Gimp popup error window message:
```
Opening
'/home/stardiviner/Screenshots/org-babel%20syntax%20highlighting%20failed.png'
failed: Could not open
'/home/stardiviner/Screenshots/org-babel%20syntax%20highlighting%20failed.png'
for reading: No such file or directory
```
I checked, this file exist.

**Comment by abo-abo** [comment]
Can you please attach an Org-mode file part that links to this file.

**Comment by stardiviner** [comment]
I found the problem. I think this is because the space in filename.
Here is two links:
```org
[[file:~/Screenshots/Screenshot_20160201_104158.png]]
[[file:~/Screenshots/org-babel%20syntax%20highlighting%20failed.png]]
```
The second filename `%20` is the space in filename.

**Comment by stardiviner** [comment]
Function `org-download-edit` should use `url-unhexify-url` to decode the link string. Then Gimp can open image path correctly.

**Comment by abo-abo** [comment]
Thanks.

**Comment by stardiviner** [comment]
Still need to escape shell path with `shell-quote-wildcard-pattern`. I created a PR here https://github.com/abo-abo/org-download/pull/34
