### ISSUE TITLE
The latest commit caused can't input URL in ivy-mode

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/org-download#36]
In this commit: https://github.com/abo-abo/org-download/commit/ec2dc69b7a49054bc0d34c6533cdcadba708db67

This caused input URL failed. Like in `ivy`, it will treat `/` in URL as `root path`.
If user want this file completing feature, I think should use a better solution.

**Comment by abo-abo** [comment]
Thanks, I've reverted it for now, until a better solution comes along.
