### ISSUE TITLE
Should this really be developed in its own repo and also be part of the Org-Mode repo?

### ISSUE THREAD

**Issue by tarsius** [abo-abo/org-download#38]
Why is `org-download.el` developed in this repository but also tracked in the contrib directory of Org-Mode's repository. I think this is problematic because it means that at least for users who install the `org-plus-contrib` package from the Org-Mode Elpa as well as `org-download` from Melpa it is undefined which version will be used (depends on the order of `load-path`).

So I would recommend that you either remove `org-download.el` from Org-Mode's contrib directory or remove `org-download` from Melpa.  If you choose to do the latter, then you might even want to consider to remove this repository and develop directly in the Org-Mode repository instead.

/cc @purcell

**Comment by tarsius** [comment]
Please also see Bastien's comment on a very similar issue: https://github.com/larstvei/ox-gfm/issues/14#issuecomment-257102966.

**Comment by purcell** [comment]
Agreed. It'd be great if some people closer to the `org` community than me were pushing for proper packaging of contrib modules. The `org-plus-contrib` situation is a monstrosity.

**Comment by abo-abo** [comment]
Thanks, fixed.

**Comment by tarsius** [comment]
Thanks a lot!

**Comment by bzg** [comment]
Thanks!
