### ISSUE TITLE
Handling base64 images "inlined" in the link

### ISSUE THREAD

**Issue by cbourjau** [abo-abo/org-download#39]
Hello,

I am using Jupyter notebooks and would like to save some plots from there to my .org file. The issue is that the plots are "inline", ie, they do not exist as a separate file but are just given by a link like ``data:image/png;base64,iVBORw0KGgoAAAANSU...``

Clearly, this is nothing ``wget`` nor ``curl`` can make sense of, but it seems like it should be easy enough to convert this base64 image to a file and treat it as usual. Unfortunately, my elisp is pretty weak. I could give it a try to make a PR if one could give me some pointers, though.

Cheers,
Christian

**Comment by abo-abo** [comment]
Please attach a sample HTML. I'll see what I can do.

**Comment by cbourjau** [comment]
Thanks for looking into this (and all your other amazing emacs packages)! An example for a jupyter noteboook with such an "inlined" figure can be found at http://www.nbi.dk/~cbourjau/ipynb_base64.html 
Cheers,
Christian

**Comment by abo-abo** [comment]
Thanks, it works for me now. Please test.

**Comment by cbourjau** [comment]
Seems to be working perfectly! Thanks a lot!
