### ISSUE TITLE
Feature request: store images in folder with the name of the org file

### ISSUE THREAD

**Issue by QiangF** [abo-abo/org-download#40]
I am a user of plain-org-wiki. The default image folder naming method use heading for folder name, many of my heading has spaces, also some are duplicate in my org-wiki directory. It would be very nice to change the image folder name from heading name to file name.
Thank you for your consideration.

**Comment by abo-abo** [comment]
Thanks, it's a good idea. I'll implement it when I have more time. PR welcome.

**Comment by lxeg0429** [comment]
try this: (setq org-download-heading-lvl nil)
and add this in your file:
# -*- eval: (setq-default org-download-image-dir (concat Emacs "Files/Images/" (file-name-sans-extension (buffer-name)))); -*-

**Comment by QiangF** [comment]
But org-download-image-dir needs to be a buffer local variable.

**Comment by lxeg0429** [comment]
try this:
# -*- eval: (setq-default org-download-image-dir (concat "c:/" (file-name-sans-extension (buffer-name)))); -*-

**Comment by QiangF** [comment]
It works, but you need to evalaluate it on every buffer before
downloading images.

**Comment by lxeg0429** [comment]
Yes, I try to set this in `init.el`, but I failed. I do not know how to set this.

I do not know how to set this `(file-name-sans-extension (buffer-name))`  in `init.el`. It will lead to error.

Maybe abo-abo can give me a hand. @abo-abo ?

**Comment by abo-abo** [comment]
@lxeg0429 You can now set `org-download-method` to your own function. See the commit message for an example.

**Comment by lxeg0429** [comment]
ok, thank you.

**Comment by daviderestivo** [comment]
In case someone is interested I wrote a function that does what requested in the first post. Comments/improvements are welcome. 
https://gist.github.com/daviderestivo/ad3dfa38d3f7266d014ce469aafd18dc

**Comment by abo-abo** [comment]
@daviderestivo Thanks for attaching an example.
