### ISSUE TITLE
Drag and drop won't work well with the latest org-ref?

### ISSUE THREAD

**Issue by diadochos** [abo-abo/org-download#42]
Thank you so much for creating this awesome package!

Drag-and-drop doesn't seem to work well with the latest version of org-ref (i.e. `7e69316cb029d46ffb505d78e8b7a5c0ee48d918` https://github.com/jkitchin/org-ref/commits/master).
When I drag-and-drop a .jpg file to a text file buffer, the jpg file is only copied to the same directory as the text file, but the link (and the corresponding headers) is not inserted.

When I roll back org-ref to `7d52d1db1f896153a8fb4aa715dcb510f643c3b0`, it works again.

It would be great if you could look into this.

**Comment by abo-abo** [comment]
I think you should also open an org-ref issue and ask @jkitchin for help.

**Comment by jkitchin** [comment]
That seems odd. I don't see any changes between those commits that would change drag and drop behavior. Can you provide a little more information about exactly what you are doing, what you expect, and what happens?

**Comment by diadochos** [comment]
Thank you so much for both of you. I will add some details later.

**Comment by abo-abo** [comment]
@jkitchin Thanks for checking.
@diadochos No problem, thanks for PR.
