### ISSUE TITLE
How to use buffer-file-name as org-download-image-dir ?

### ISSUE THREAD

**Issue by diadochos** [abo-abo/org-download#46]
Hi, thank you for the great library.
This is a question rather than an issue.

I would like to set `org-download-image-dir` to the current file name. Is it possible with the current version?
(For example, when drag-and-dropped `foo.jpg` to `bar.org`, I would like to have `./bar-img` directory to be created, and have `foo.jpg` in there.)

Thanks in advance!

**Comment by abo-abo** [comment]
Something like this:

```elisp
(defun my-org-download-method (link)
  (let ((filename
         (file-name-nondirectory
          (car (url-path-and-query
                (url-generic-parse-url link)))))
        (dirname (concat (file-name-sans-extension (buffer-name)) "-img")))
    (make-directory dirname)
    (expand-file-name filename dirname)))
(setq org-download-method 'my-org-download-method)
```

**Comment by diadochos** [comment]
@abo-abo : Thanks a lot for the snippet! Will try something like that.

**Comment by diadochos** [comment]
I ended up with the following monkey-patch.
```
(defun org-download--dir-1 ()
  (or org-download-image-dir (concat (file-name-sans-extension (buffer-name)) "-img")))
```
To apply this, one can add the above snippet to their .emacs.d .

**Comment by AtomicNess123** [comment]
Is it possible to then use: 

`(setq-default org-download-image-dir (concat (file-name-sans-extension (buffer-file-name)) "-img")))`?

**Comment by akashpal-21** [comment]
> Is it possible to then use:
> 
> `(setq-default org-download-image-dir (concat (file-name-sans-extension (buffer-file-name)) "-img")))`?
> 
> With this, I get always "init" as the name for the subdirectory.

```

(defun custom/org-download-dir ()                                                            
  "Download files in ./resources/$filename/"
  (setq-local org-download-image-dir (concat
				     "./resources/"
				      (file-name-sans-extension (buffer-name))
				      "/")
	      )                                                                                                         ; Store downloads in ./resources/%filename/
  )                                                                                                                     ; relative to the .org file
(add-hook 'org-mode-hook 'custom/org-download-dir)

```
