### ISSUE TITLE
Extend this package to work in markdown mode

### ISSUE THREAD

**Issue by fabrik42** [abo-abo/org-download#47]
Hi! First of all, thank you for this lib! I was looking for something like this and I did not expect to find something that works so well and comes so close to my needs.

I would like to use this functionality in combination with [deft](http://jblevins.org/projects/deft/), but I prefer to use the markdown mode, rather than the org mode. Would it be possible to extend `org-download` to also work in markdown mode?

Thanks,
Christian

**Comment by abo-abo** [comment]
It's possible to do, but I'm not really interested in `markdown-mode`. You can reuse some `org-download` functions to build your own setup for `markdown-mode`.

**Comment by fabrik42** [comment]
Thank you for the fast reply! I will try to put something together myself. :)

**Comment by fab6** [comment]
Hi @fabrik42 and others,
I am looking for a way to paste screenshots to markdown and was wondering if anyone maybe knows some new implementation which does this or knows how to achieve this?
At the moment I am using this on a macos
```
(defun fb-md-screenshot ()
  "Take a screenshot into a time stamped unique-named file in the
same directory as the org-buffer and insert a link to this file."
  (interactive)
  (let ((filename
         (concat
          (make-temp-name
           (concat "./img/" 
                   (format-time-string "screen_%Y%m%d_%H%M%S_")) ) ".png")))
    (call-process "/usr/sbin/screencapture" nil nil nil "-i" filename)
    (insert (concat "![](" filename ")"))
    ))
```
but it would be nice to have some additional features for markdown (e.g. that it recognizes the current 1st level header to use as a subfolder.
Thanks!
