### ISSUE TITLE
How to add a timestamp to the file name?

### ISSUE THREAD

**Issue by zhixing2017** [abo-abo/org-download#48]
I modified the code [use buffer-file-name as org-download-image-dir ](https://github.com/abo-abo/org-download/issues/46) to make it work better for me.
But I do not know how to add a timestamp to the `filename`.
Can you help me? Thank you!

```
(defun zhixing-org-download-method (link)
  (let ((filename
         (file-name-nondirectory
          (car (url-path-and-query
                (url-generic-parse-url link)))))
        (dirname (concat Files "Images/" (file-name-sans-extension (buffer-name)) "-img"))
        )
    (make-directory dirname :parents)
    (expand-file-name filename dirname)))
```

**Comment by zhixing2017** [comment]
I've figured it out.  Sorry for bothering.
Replacing the filename at the last line with below code worked.

 ```
    (format "%s%s.%s"
             (file-name-sans-extension filename)
             (format-time-string "_%Y-%m-%d_%H-%M-%S")
             (or ext (file-name-extension filename)))
```

**Comment by abo-abo** [comment]
I'm glad you solved to problem:) I like to help, but sometimes I'm busy with other things.
