### ISSUE TITLE
rename the file downloaded

### ISSUE THREAD

**Issue by dinojr** [abo-abo/org-download#50]
It would be very convenient to have org-download prompt for a filename for the downloaded file.

**Comment by abo-abo** [comment]
I don't think it would work nicely. As you drag with the mouse, you are likely to select the window you're dragging to. But any input for the file name is done in the minibuffer. So you have to type something, but sometimes the wrong window is selected.

**Comment by abo-abo** [comment]
But it's possible to add something like `org-download-rename-last-file`.

**Comment by wandersoncferreira** [comment]
Hi,

I added a PR #58  to provide this functionality of `org-download-rename-last-file`.

Pls, let me know if there are anything I can do to improve it.

Thx for the package.

**Comment by abo-abo** [comment]
@wandersoncferreira Thanks for the PR. I've added some minor comments that need a fix.

**Comment by abo-abo** [comment]
The PR is merged, so I close this.

**Comment by abo-abo** [comment]
The PR is merged, so I close this.

**Comment by abo-abo** [comment]
The PR is merged, so I close this.

**Comment by abo-abo** [comment]
The PR is merged, so I close this.
