### ISSUE TITLE
How to delete the original picture after draged from local disk by org-download-method?

### ISSUE THREAD

**Issue by zhixing2017** [abo-abo/org-download#53]
Hello.
Below is my code for `org-download-method`. After draged into the org-mode files, the pictures were saved in the new place.
Is there any way easily to delete the original pictures? 
I do not know much about `emacs-lisp`, can you help me with this? Thank you in advance.

``` emacs-lisp
(defun zx-org/org-download-method (link)
  (let ((filename
         (file-name-nondirectory
          (car (url-path-and-query
                (url-generic-parse-url link)))))
        (dirname (concat "Images/" (file-name-sans-extension (buffer-name)) "-img/")))
    (unless (f-exists-p dirname)
      (make-directory dirname :parents))
    (expand-file-name (format "%s.%s"
                              (format-time-string "%Y-%m-%d_%H-%M-%S")
                              (or ext (file-name-extension filename)))
                      dirname)))
```

**Comment by abo-abo** [comment]
Here's your code, slightly cleaned up:

```elisp
(setq org-download-method 'zx-org/org-download-method)
(defun zx-org/org-download-method (link)
  (let ((filename
         (file-name-nondirectory
          (car (url-path-and-query
                (url-generic-parse-url link)))))
        (dirname (concat "Images/" (file-name-sans-extension (buffer-name)) "-img/")))
    (unless (file-exists-p dirname)
      (make-directory dirname :parents))
    (expand-file-name (format "%s.%s"
                              (format-time-string "%Y-%m-%d_%H-%M-%S")
                              (file-name-extension filename))
                      dirname)))
```

Here's how you can use Elisp advice:

```elisp
(advice-add 'org-download-insert-link :after 'zx-org/delete-file)
(defun zx-org/delete-file (link filename)
  (setq link (org-link-unescape link))
  (let ((filename (and (string-match "\\`file://\\(.*\\)\\'" link)
                       (match-string 1 link))))
    (when (and filename
               (file-exists-p filename))
      (delete-file filename t))))
```

Be careful with `delete-file`, there's no way to undo it unless you hook it up to delete to trash.

**Comment by zhixing2017** [comment]
Thank you very much.
However, after added into my init.el, it did not works well. 
Can the two func be merged into one? I do not know how to make the second func work.
Regards.

**Comment by abo-abo** [comment]
Try to edebug on `zx-org/delete-file`, see where it goes wrong.

**Comment by zhixing2017** [comment]
I have no idea with the `debug`. No error, no warning. 
Could you give me some tips?

**Comment by abo-abo** [comment]
Move cursor inside function, press <kbd>C-u C-M-x</kbd>. Drag-and-drop something, the debugger will jump to function. Step through the debugger with `SPC`.

**Comment by zhixing2017** [comment]
It shows this:
![default](https://user-images.githubusercontent.com/26316963/27875526-0c5c2d7a-61e6-11e7-8019-b69dc2d7fcbf.png)
It looks like the line 50 is not appropriate.

**Comment by abo-abo** [comment]
That's fine, it means you stepped into the debugger. Just keep pressing `SPC` until you exit from the function. Then look at your `*Messages*` buffer.

**Comment by zhixing2017** [comment]
This method is amazing, Thank you.
Here are the messages:
```
Edebug: zx-org/delete-file
user-error: All variables and subroutines might as well have a documentation string
Wrote d:/Documents/Files/Temp.org
 [2 times]
Result: "file:D%3A/Pictures/runemacs.jpg"
Result: "file:D:/Pictures/runemacs.jpg"
Result: "file:D:/Pictures/runemacs.jpg"
 [4 times]
Result: "file:D:/Pictures/runemacs.jpg"
Result: nil
Result: nil
 [3 times]
Result: nil
Result: nil
Result: nil
Result: nil
```
From the *Messages*, this func can find the path. But it did not delete the file. Maybe there is something wrong with the "find-delete" part. I do not know much. Need you help, thanks.

**Comment by abo-abo** [comment]
Updated code:

```elisp
(defun zx-org/delete-file (link filename)
  (setq link (org-link-unescape link))
  (let ((filename (and (string-match "\\`file:\\(.*\\)\\'" link)
                       (match-string 1 link))))
    (when (and filename
               (file-exists-p filename))
      (delete-file filename t))))
```

**Comment by zhixing2017** [comment]
It works. Thank you very much.

**Comment by abo-abo** [comment]
Glad to help.
