### ISSUE TITLE
Screenshot directory on windows

### ISSUE THREAD

**Issue by technician77** [abo-abo/org-download#54]
After setting org-download-screenshot-method to imagemagick/convert I try org-download-screenshot.
Then I get the messages below. ImageMagick 6.9.9 64bit is installed. I run emacs 25.2 on windows.

It seems the directory is in Unix format and not existing. Where do I set the directory? Couldn't find that in customize. Org-download-image-dir is currently set to `c:/home/username/tmp/`

```
convert.exe: unable to open image `/tmp/screenshot.png': No such file or directory @ error/blob.c/OpenBlob/2701.
convert.exe: WriteBlob Failed `/tmp/screenshot.png' @ error/png.c/MagickPNGErrorHandler/1647.
url-retrieve-internal: Bad url: /tmp/screenshot.png
```

**Comment by dinkonin** [comment]
Had the same problem, my workaround was to override  `org-download` in my config like this

```elisp
(eval-after-load "org-download"
'(defun org-download-screenshot ()
  "Capture screenshot and insert the resulting file.
The screenshot tool is determined by `org-download-screenshot-method'."
  (interactive)
  (let ((link "C:/temp/screenshot.png"))
    (shell-command (format org-download-screenshot-method link))
    (org-download-image link)
    (delete-file link)
    ))
```
I've changed the `link` variable to a temp directory that I use and also added `(delete-file link)` to dispose of the temp file (not necessary if you clean your temp by other means)

**Comment by abo-abo** [comment]
@dinkonin Nice fix. I didn't expect `org-download-screenshot` to work on Windows.

**Comment by abo-abo** [comment]
You can now use `(setq org-download-screenshot-file "C:/temp/screenshot.png")`.
