### ISSUE TITLE
How can I paste image from copyq

### ISSUE THREAD

**Issue by amosbird** [abo-abo/org-download#56]
Hi, is it support to paste images from `copyq` ? I saw there is a backend `xclip` but it doesn't work.

**Comment by abo-abo** [comment]
I don't know what `copyq` is, please elaborate. What's your system?

**Comment by amosbird** [comment]
it's archlinux I'm using. `copyq` is a clipboard manager which seems not relevant though. I think it should be the same as `xclip -selection clipboard -t image/png -i example.png`. I'd like to put current clipboard's image into `org` buffer.

**Comment by abo-abo** [comment]
I wasn't the one who added the `xclip` functionality. If you want to fix/improve/extend it, feel free to PR.

**Comment by azzamsa** [comment]
@amosbird paste image from clipboard was supported [long before you asked](https://github.com/abo-abo/org-download/commit/131d2409b3639798ebac6d77c98eae446ea915dc)

You just need to add:
`(setq org-download-screenshot-method "xclip -selection clipboard -t image/png -o > %s")`
in your config. After you had an image in clipboard. just call `org-download-screenshot`
