### ISSUE TITLE
Screenshot only working when it already exists in clipboard

### ISSUE THREAD

**Issue by technician77** [abo-abo/org-download#57]
Maybe it's just a misunderstanding. When I use org-download-screenshot it only works when the screenshot is already in the clipboard. Is this intended? The paragraph below suggests to me that it takes a screenshot itself. I work on windows using emacs-nt.

My settings are:
```
   (setq-default org-download-image-dir "~/temp")
   (setq org-download-screenshot-file "Z:/home/myuser/temp/screenshot.png")
   (setq org-download-screenshot-method "convert clipboard: %s"))

```
The output when there is no picture in the clipboard:
```
convert.exe: no bitmap on clipboard `' @ error/clipboard.c/ReadCLIPBOARDImage/143.
convert.exe: no images defined `Z:/home/myuser/temp/screenshot.png' @ error/convert.c/ConvertImageCommand/3258.

```
From the frontpage:
> A screenshot taken using gnome-screenshot, scrot, gm, xclip (on Linux), screencapture (on OS X) or , imagemagick/convert (on Windows). Use the org-download-screenshot command for this. Customize the backend with org-download-screenshot-method.

**Comment by abo-abo** [comment]
@technician77 Please ping the author of the feature, I don't really know how to answer you.

**Comment by technician77** [comment]
Code suggest it seems to be intended that way. The wording on the frontpage might have been missleading for me.
