### ISSUE TITLE
Very useful

### ISSUE THREAD

**Issue by usharf** [abo-abo/org-download#59]
This is so useful for me right now (taking notes with emacs in interleave mode), I'm really happy I've come across your code! Still need to setup a permanent folder where screenshots should go, of course.

(text is Hebrew & Arabic) I'm taking a screenshot of part of the PDF (on the left), which gets auto-magically inserted/embedded in the document I'm editing (on the right), using the screenshot feature (`org-download-screenshot`, of Linux (Ubuntu). Seamless, and VERY handy.

![screenshot from 2017-11-09 11-06-56](https://user-images.githubusercontent.com/1701421/32599983-6774841c-c53e-11e7-9fb5-71711229ff90.png)

Just wanted to say thanks :+1:

**Comment by abo-abo** [comment]
You're welcome. Thanks for posting, your screenshot looks very cool.
