### ISSUE TITLE
Error 'wrong-type-argument' when rename image at point

### ISSUE THREAD

**Issue by et2010** [abo-abo/org-download#62]
I bumped into this error when I was trying to rename image at point. To clarify a bit, I was working with evil normal state and the inline image was toggled on.

I think this is caused by `ffap-file-at-point` not working in this case. I've created a PR to use org-element API instead of `ffap-file-at-point` to get the filename at point.

**Comment by abo-abo** [comment]
> I think this is caused by ffap-file-at-point not working in this case.

Can you elaborate on this? I think there's no reason for `ffap-file-at-point` to not work when it's indeed on a file name.

**Comment by et2010** [comment]
> I think there's no reason for ffap-file-at-point to not work when it's indeed on a file name.

It seems the cursor is not on a file name when the image is displayed.

**Comment by abo-abo** [comment]
OK, merged. Thanks.
