### ISSUE TITLE
How to install this using package?

### ISSUE THREAD

**Issue by whatacold** [abo-abo/org-download#66]
Hi,
It it possible to install this packaged from melpa, I failed to do so. My package archives is:

    (setq package-archives
    '(("localelpa" . "~/.emacs.d/localelpa/")
           ("melpa" . "http://melpa.org/packages/")
           ("melpa-stable" . "http://stable.melpa.org/packages/")))

This package is not listed in `M-x list-packages`, after doing `package-refresh-contents`.
What did I do wrong?

**Comment by abo-abo** [comment]
I see nothing wrong with your config. This is likely a MELPA issue, please report it here: https://github.com/melpa/melpa.

**Comment by whatacold** [comment]
Hi,
Just figured out that it was filtered out in my config, see [package-filter-function](https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-elpa.el#L104) for detail,
and it has nothing to do with melpa, thanks for your help.
