### ISSUE TITLE
org-mode capture template function for putting an URL and outputting the file path of the file downloaded to disk

### ISSUE THREAD

**Issue by shackra** [abo-abo/org-download#67]
I'm having this use case where I try to use org-download as part of a org-mode capture template. However I can't figure how to use it correctly to place the string after the file was downloaded to disk.

What I have is this:

```
("r" "Receta de cocina" entry (file "recetas.org")
             "* %^{Nombre de la receta}\n:PROPERTIES:\n:CREATED: %T\n:END:\n%?\n%(call-interactively 'org-download-image)\n- Sacado de: %^a\n** Ingredientes\n** Procedimiento"
             :kill-buffer t :clock-in t :clock-resume t)
```

Which doesn't work because I honestly don't know what I'm doing. Thus, providing a elisp function for this job may be good idea.

**Comment by abo-abo** [comment]
Where's the image coming from? It doesn't look like you drag and drop it.

**Comment by shackra** [comment]
The idea was to input the image URL

**Comment by moritzschaefer** [comment]
bump
I tried this:

```
     ("r" "Receipt" entry
      (file+olp+datetree "~/wiki/receipts.org")
      (format "* %%? %%(org-download-image %s)" moritzs/recent-smartphone-photo)
```

without success. moritzs/recent-smartphone-photo returns a path to an image. 
(org-download-image (moritzs/recent-smartphone-photo)) (I could actually do this without the format...) works well if not called from within the template. Problem seems to be that org-download does not know where to write the link after downloading the image..

Any ideas on how to workaround?

**Comment by abo-abo** [comment]
@moritzschaefer, this code works for me:

```elisp
(defun org-download-capture (url)
  (let* ((org-download-image-dir (expand-file-name "~/Pictures/org-download"))
         (org-download-abbreviate-filename-function #'expand-file-name)
         (str (org-download-image url)))
    (sit-for 0.01)
    str))

(setq org-capture-templates
      '(("i"
         "Image"
         entry
         (file+olp+datetree
          "~/Dropbox/org/wiki/images.org")
         "* %?\n%(org-download-capture (current-kill 0))\n")))
```

Please test if you can adapt this to your needs.
