### ISSUE TITLE
org-download-heading-lvl does not accept a value of nil

### ISSUE THREAD

**Issue by ephsmith** [abo-abo/org-download#74]
Either the documentation is incorrect or the function of `org-download-heading-lvl` is incorrect. 

The variable `org-download-heading-lvl` currently expects an integer and therefore cannot be set to (customized) a `nil` value as the README prescribes. 

Version Info:
- GNU Emacs v25.1.1
- Orgmode v9.1.13 
-`org-download` Elpa-org-download-20180327

**Comment by nsushkin** [comment]
So, how did you customize the variable? Is manually editing .emacs the only way or you can coax org-download customize buffer to set the variable to nil?

**Comment by abo-abo** [comment]
Thanks, fixed. Sorry for the delay.
