### ISSUE TITLE
Paste from Clipboard on Windows possible?

### ISSUE THREAD

**Issue by poulpoulsen** [abo-abo/org-download#75]
Hello, i use org-download with drag and drop images on Windows and it works.
But paste an image is not.
The following message appears and no image is loaded.
File "IMG_20180527_084811_2018-06-12_19-24-13.jpg" is now a task attachment.
Under the org-heading appears the following,but no image. I toggle with org-toggle-inline-image, but nothing happens.
"        :PROPERTIES:
:ID:       49578a89-39ed-425c-810c-c4b085699000
:Attachments: IMG_20180527_084811_2018-06-12_19-24-13.jpg
:CREATED:  <2018-06-12 Di 19:24>
:END:

#+DOWNLOADED: file:C%3A/Users/Held/Desktop/IMG_20180527_084811.jpg @ 2018-06-12 19:24:13
#+attr_html: :width 100px
*
Any clues?

Regards
Poul

**Comment by TobiasZawada** [comment]
Hi abo-abo,
FYI: This question is connected to a [question answer pair about pasting base64-encoded images in org-mode](https://emacs.stackexchange.com/a/41664/2370) on https://emacs.stackexchange.com.

There the variables `org-download-screenshot-method` and `org-download-screenshot-file` are used for function `org-download-screenshot-img`.

In [a comment](https://emacs.stackexchange.com/questions/41544/is-it-possible-to-include-a-base64-image-in-org-file/41664?noredirect=1#comment65939_41664) the OP gave following statement:

> hello, i checked again with imagemagick installed. Unfortunately it is not working as aspected. If i copy an image into the windows clipboard and tried to insert the image with C-S-y. The following message occur: "convert: NoBitmapOnClipboard ' @ error/clipboard.c/ReadCLIPBOARDImage/158. convert: NoImagesDefined ~/screenshot.png' @ error/convert.c/ConvertImageCommand/3275. let: Opening input file: No such file or directory, c:/Users/Held/screenshot.png" Is it possible to insert the image via clipboard and copy/paste? Regards – space_held

I find the message **`convert: NoBitmapOnClipboard`** rather interesting.

**Comment by TobiasZawada** [comment]
Imagemagick is compiled with [MS-VisualStudio](http://imagemagick.sourceforge.net/http/www/windows.html#260). Therefore we need an additional `expand-file-name` to expand the tilde character `~` to the users home directory.

**Comment by poulpoulsen** [comment]
hello, i try it with the double slashes. Result is: "convert: NoImagesDefined `c:\\Users\\Held\\screenshot.png' @ error/convert.c/ConvertImageCommand/3275.
url-scheme-default-loader: Unknown URL scheme: c"
Does it help?
Regards
Poul

**Comment by TobiasZawada** [comment]
@poulpoulsen Dear Poul,
issue #57 describes a similar problem. In some way it answers two questions:
1. Pasting images from the clipboard should work in principle on Windows. (Otherwise #57 would not have been closed.)
2. The problem there was that @technician77 misinterpreted the documentation. I would even say that this is a documentation bug and a misnaming of `org-download-screenshot` for Windows. The Emacs command `org-download-screenshot` does **not** take the screenshot. It just pastes an image that is already on the clipboard as attachment into an org-buffer.
But, I assume that you know that and that you are facing a different problem.

**Comment by TobiasZawada** [comment]
@poulpoulsen 
It may be that you copy image data to the clipboard that cannot be read by Imagemagick, e.g., handles to emf and wmf images.
See: http://www.multipole.org/discourse-server/viewtopic.php?t=20303

**Comment by et2010** [comment]
Hi, @poulpoulsen 

FYI, Irfanview on Windows can be used to take a screenshot. It's free for personal use. I've just created a PR for this purpose. You can try it.

**Comment by falematte** [comment]
It looks like this problem is not only windows related. I am not able to do the same in linux.

**Comment by abo-abo** [comment]
@falematte Please elaborate. Write down a list of steps for me to follow.

**Comment by falematte** [comment]
Thank you for the answer. I am able to drag and drop images but pressing C-y the image saved in the clipboard is not inserted in the buffer.

**Comment by abo-abo** [comment]
@falematte

I have just tested it on Linux like this. I set `org-download-screenshot-method` to one of the available settings:

```elisp
(setq org-download-screenshot-method
      "xclip -selection clipboard -t image/png -o > %s")
```

- I open an image in GIMP and copy to clipboard.
- Open an Org file and <kbd>M-x</kbd> `org-download-screenshot`

Everything works as expected.

**Comment by MorphicResonance** [comment]
Org-download screenshot works on Windows 10. Got screenshot from clipboard and pasted into org file. 
Tested with windows default  _Snip & Sketch tool_ and _convert_ from imagemagick
Took screenshot by windows _Snip & Sketch tool_. It takes screenshot and puts it into the clipboard. Picture is exist and can be pasted  somewhere (checked on imgur).

 _org-download-screenshot-method_ was set to run imagemagick and process clipboard. Tried with Infartview also.
Part of config.el from doom emacs.
`  (setq org-download-screenshot-method "convert clipboard: %s")
  (setq org-download-method '+org/org-download-method))`

Steps taken to make it works. 
• install imagemagick for windows. During installation check box to install convert.exe
![image](https://user-images.githubusercontent.com/55984436/86299679-888eaa00-bc09-11ea-8ece-0dee9ee11fdb.png)
• make sure you have imagemagick path to your system variables.

**Comment by falematte** [comment]
> @falematte
> 
> I have just tested it on Linux like this. I set `org-download-screenshot-method` to one of the available settings:
> 
> ```emacs-lisp
> (setq org-download-screenshot-method
>       "xclip -selection clipboard -t image/png -o > %s")
> ```
> 
>     * I open an image in GIMP and copy to clipboard.
> 
>     * Open an Org file and M-x `org-download-screenshot`
> 
> 
> Everything works as expected.

Everything works perfectly for me!

**Comment by zzamboni** [comment]
For reference (since I ended up on this thread while figuring out how to do this), on macOS a similar technique can be used to paste an image from the clipboard, by setting `org-download-screenshot-method` to `"/usr/local/bin/pngpaste %s"` (pngpaste can be installed from Homebrew). Then you can copy a screenshot or image to the clipboard and use `M-x org-download-screenshot` to insert it.

**Comment by abo-abo** [comment]
Thanks, all, for the comments and suggestions. Please test the new `org-download-clipboard`, which should work for GNU/Linux, Windows, and OSX.

**Comment by Exr0n** [comment]
Hi, this was closed a while ago but I'm confused about how to use `org-download-clipboard`. I couldn't find any documentation or even a mention of it except here... where can I learn how to install and use it?

**Comment by zzamboni** [comment]
@Exr0n if it helps, here's my configuration: https://github.com/zzamboni/dot-doom/blob/master/doom.org#capturing-images

(some Doom Emacs-specific stuff there, like `after!` and `map!`, but which should be easily switchable to vanilla versions)

**Comment by hydev** [comment]
Just for reference, on Windows it is possible to use `org-download-screenshot` without using imagemagick convert, but by using powershell:
```
(setq org-download-screenshot-method "powershell -c Add-Type -AssemblyName System.Windows.Forms;$image = [Windows.Forms.Clipboard]::GetImage();$image.Save('%s', [System.Drawing.Imaging.ImageFormat]::Png)")
```
