### ISSUE TITLE
Improve documentation? 

### ISSUE THREAD

**Issue by jarss** [abo-abo/org-download#78]
Hi. Definitely not a programmer, and new to emacs. 

Lots of the terms used in the documentation are unclear for beginners, and even though I have my settings in an org file, I'm still not clear on what needs to be set up, where, and how. 

Perhaps an example of how this works (basic setup) would be a good idea? 

Thank you :)

**Comment by abo-abo** [comment]
If you can improve the documentation, feel free to PR. This bit of config (already in README) is enough to set up the defaults:

    (add-hook 'dired-mode-hook 'org-download-enable)

**Comment by mrspeaker** [comment]
Where do I add that config? Do I need to download this repo somewhere or does that command you pasted also magically download it?

**Comment by sjatkins** [comment]
I agree. The documentation is inadequate.  Do not assume your reader is well enough versed in elisp and emacs to understand your docs.  I think I am a bit more than a newbie in that department and it does not work for me.  Nor can I find the apparent variables and function referred to after a package manager install. 

So something is wrong.

**Comment by sjatkins** [comment]
Short of it is dragging image from the net to my org file after reload of .emacs with the hook does nothing.  So I am misconstruing something.

**Comment by abo-abo** [comment]
I've added `(require 'org-download)` to the set up code. That's the only code you need to get the basics working. Other than that, you can explore with `customize-group` `org-download`.
