### ISSUE TITLE
Use relative file names

### ISSUE THREAD

**Issue by HaoZeke** [abo-abo/org-download#79]
The current implementation implies:

```lisp
    (setq-default org-download-image-dir "./foo")
```
Should make the link be `file:foo/img.png` however it is `file:FULLPATH/foo/img.png` which breaks pandoc and latex exports.

**Comment by HaoZeke** [comment]
Sorry, my bad, I was using the `doom-emacs` config which forced all paths to be absolute.


Great package by the way!

**Comment by abo-abo** [comment]
No problem, and thanks.
