### ISSUE TITLE
what qualifies as a "A local or remote image address" for org-download-yank

### ISSUE THREAD

**Issue by shu-cheng** [abo-abo/org-download#82]
When I copy an image from a PDF and org-download-yank into an emacs file, I encouter:

> url-retrieve-internal: Bad url: %20

although I can successfully paste it into a Word doc.
It seems that the images has to have an "address", can you give more explanations for this?

Thank you for this great package!

**Comment by abo-abo** [comment]
> It seems that the images has to have an "address", can you give more explanations for this?

It needs to be a local file name or a remote URI.

However, you can use `org-download-screenshot` to grab an image from the clipboard (which you got from PDF).

```elisp
(setq org-download-screenshot-method
      "xclip -selection clipboard -t image/png -o > %s")
```

You need `xclip` program for this:

```elisp
sudo apt install xclip
```

**Comment by shu-cheng** [comment]
Yeah, that's what I was looking for, although somehow, xclip doesn't work on my mac when specifying image/png. But I tried pngpaste, and now it works like a charm.

Thanks a lot!

**Comment by yitang** [comment]
@shu-cheng Please could you share your setup? I tried 

(setq org-download-screenshot-method
      "pngpaste %s")

but it doesn't work.

**Comment by shu-cheng** [comment]
@yitang 

That's exactly what I have in my setup... My other setups of org-download are pretty standard, and should not affect this the screenshot function much.

This is all I have

```
  (setq org-download-screenshot-method "pngpaste %s")
  (setq org-download-method 'directory)
  (setq-default org-download-heading-lvl nil)
  (setq-default org-download-image-dir "./attached_images")

```
