### ISSUE TITLE
Images with spaces in filename result in filepath with encoding

### ISSUE THREAD

**Issue by damoen** [abo-abo/org-download#83]
Images with spaces in filename do not display for me as the spaces gets replaced with %20 in path.
Images without spaces in filename however display just fine.

![org-download](https://user-images.githubusercontent.com/1279519/47212133-a1a0ea00-d397-11e8-9e1b-f38a650e9e6e.png)

I am fairly new to Emacs so I guess the culprit could lie ouside of org-download but I wanted to ask here first. My config files are messy but if you care to take a look, [here they are](https://github.com/damoen/home/tree/master/.emacs.d).

**Comment by jethrokuan** [comment]
I came here to also post a similar issue. I'd like, as much as possible, to avoid spaces in file paths when using org-download.

AFAIK, I can only configure the first part of `org-download-dir`. The second part, which comes from `org-download-heading-lvl`, does not let me substitute spaces in the headings with something else (e.g. underscores). It is also not possible for me to substitute the file name if I'm downloading it from the internet.

**Comment by abo-abo** [comment]
Can't reproduce on Emacs 26.1 and Org-mode @(ba321d0e4, Jan 13 15:14:37 2019).

    #+DOWNLOADED: file:///home/okr/Pictures/org-download/image%201.jpeg @ 2019-01-17 15:21:22
    <picture is displayed here>

**Comment by GregorySchwartz** [comment]
Is it possible to have a variable to customize spaces or the name itself?

**Comment by abo-abo** [comment]
Let's try to clarify if the issues with file names in spaces are due to `org-mode`, and on which platform they are reproducible.

We can then see if the underlying problem can be fixed, rather than jumping into making work-arounds in `org-download`. If the underlying problem can't be solved, I can add a work-around.

**Comment by jethrokuan** [comment]
The issue is with exporting to latex, which doesn't like spaces or `%20`s.

Issue:

1. Run `emacs -Q`
2. `(require 'org-download)
3. Create test.org with
```
* Header with spaces
```
4. `org-download-screenshot`

Resultant org-file:
```
* Heading with spaces

#+DOWNLOADED: /tmp/screenshot.png @ 2019-02-14 22:26:17

[[file:Heading%20with%20spaces/screenshot_2019-02-14_22-26-17.png]]
```

`C-c  C-e l p` -> error, no pdf file produced

```
Runaway argument?
{Heading\end {center} \end {document} 
! File ended while scanning use of \Gin@ii.
<inserted text> 
                \par 
<*> test.tex
            
! Emergency stop.
<*> test.tex
            
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on .//test.log.
```

**Comment by jethrokuan** [comment]
fwiw, I provide my own org-download-method to get around the issues with space:

```
(defun my-org-download-method (link)
    "This is a helper function for org-download.
It creates a folder in the root directory (~/.org/img/) named after the
org filename (sans extension) and puts all images from that file in there.
Inspired by https://github.com/daviderestivo/emacs-config/blob/6086a7013020e19c0bc532770e9533b4fc549438/init.el#L701"
    (let ((filename
           (file-name-nondirectory
            (car (url-path-and-query
                  (url-generic-parse-url link)))))
          ;; Create folder name with current buffer name, and place in root dir
          (dirname (concat "./images/"
                           (replace-regexp-in-string " " "_" (downcase (file-name-base buffer-file-name))))))

      ;; Add timestamp to filename
      (setq filename-with-timestamp (format "%s%s.%s"
                                            (file-name-sans-extension filename)
                                            (format-time-string org-download-timestamp)
                                            (file-name-extension filename)))
      ;; Create folder if necessary
      (unless (file-exists-p dirname)
        (make-directory dirname))
      (expand-file-name filename-with-timestamp dirname)))
  (setq org-download-method 'my-org-download-method)
```

**Comment by abo-abo** [comment]
Thanks. Please test.

**Comment by ugurbolat** [comment]
> fwiw, I provide my own org-download-method to get around the issues with space:
> 
> ```
> (defun my-org-download-method (link)
>     "This is a helper function for org-download.
> It creates a folder in the root directory (~/.org/img/) named after the
> org filename (sans extension) and puts all images from that file in there.
> Inspired by https://github.com/daviderestivo/emacs-config/blob/6086a7013020e19c0bc532770e9533b4fc549438/init.el#L701"
>     (let ((filename
>            (file-name-nondirectory
>             (car (url-path-and-query
>                   (url-generic-parse-url link)))))
>           ;; Create folder name with current buffer name, and place in root dir
>           (dirname (concat "./images/"
>                            (replace-regexp-in-string " " "_" (downcase (file-name-base buffer-file-name))))))
> 
>       ;; Add timestamp to filename
>       (setq filename-with-timestamp (format "%s%s.%s"
>                                             (file-name-sans-extension filename)
>                                             (format-time-string org-download-timestamp)
>                                             (file-name-extension filename)))
>       ;; Create folder if necessary
>       (unless (file-exists-p dirname)
>         (make-directory dirname))
>       (expand-file-name filename-with-timestamp dirname)))
>   (setq org-download-method 'my-org-download-method)
> ```

I cloud not get this snippet work :/ 
When I placed it in my init.el file, it disables the org-download totally... Neither original org-download works nor your snippet...
