### ISSUE TITLE
org downloaded %-escapes image paths which makes latex export fail

### ISSUE THREAD

**Issue by moritzschaefer** [abo-abo/org-download#84]
When using org-download-screenshot in Spacemacs, it copies the image into a folder named after the org-heading. If this heading contains a whitespace, then the created folder contains a whitespace and the link inserted into the org-document contains a link with a URL encoded path (i.e. the space character becomes %20). This is not a problem within org mode but when export to Latex, the file is not found (as Latex presumably does not handle URL encoded paths correctly) and Latex fails to export the document.

**Comment by abo-abo** [comment]
I think the issue should be raised against Org-mode. Having a valid org link to a folder with spaces in it should work fine with `ox-latex`.
