### ISSUE TITLE
Possibility to extract part of the code to a standalone package 

### ISSUE THREAD

**Issue by asok** [abo-abo/org-download#85]
Hi, lately I was looking into possibility to allow displaying remote images in `markdown-mode`, jrblevin/markdown-mode#316.
I see that the function `org-download--image/url-retrieve` does already what I was trying to code. Have you ever thought about extracting part of the code that downloads a remote files to a separate package?

**Comment by abo-abo** [comment]
I don't think it's worthwhile to extract here: `url.el` does all the heavy lifting, I just have a small wrapper.

You could depend on `org-download`, if you don't mind bringing in `org` as a dependency.

**Comment by asok** [comment]
Thanks for addressing that. In the meantime markdown-mode added the support for downloading images https://github.com/jrblevin/markdown-mode/pull/378 
So for me this issue is closed.
