### ISSUE TITLE
org-download inserting the wrong path to the image.

### ISSUE THREAD

**Issue by beetleb** [abo-abo/org-download#87]
I kept getting this weird issue where it would save the file in the correct location, but the link it would insert would always be one directory above. 

As an example, it would save the file in "images/" directory, but the link would be "../images/filename.png"

Digging into the code, it looks like this is the culprit:

`(file-relative-name filename (file-name-directory (buffer-name)))`

I don't think you should use buffer-name. In my case, the name of my buffer was "misc.org/misc". This is because the filename is misc.org, and I have two misc.org files open in Emacs - in different directories (this one was in a directory called "misc"). The uniquify package changes the buffer names to help distinguish between the two. 

Perhaps you should do the following instead:

`(file-relative-name filename (file-name-directory default-directory))`

**Comment by abo-abo** [comment]
Thanks, please test.
