### ISSUE TITLE
org-download and relative path instead of absolute problem

### ISSUE THREAD

**Issue by falematte** [abo-abo/org-download#88]
I love org download and it works like a charm. Anyway if you use a single folder for storing all the images you get links like this one:

[[file:../orgpic/Selection__NNN(049)_2018-12-06_18-09-22.jpg]]

and, if the link is moved inside an org file in a different folder (maybe because you refile it), it can become useless because the relative path is no longer accurate. I think an option to use the absolute path would be really a great improvement.

**Comment by abo-abo** [comment]
Thanks, you can now use this code:

```elisp
(setq org-download-abbreviate-filename-function 'expand-file-name)
```
