### ISSUE TITLE
Adding an extra enter or new line after a drag and drop of image

### ISSUE THREAD

**Issue by michaelsjackson** [abo-abo/org-download#93]
This would help, you can easily continue adding another image, or just write some text. Now you have to hit enter first, plus switching over to emacs. This feature would save you those three steps:
- switch to emacs
- add enter
- switch back to your previous window, like browser

clipmon, on the other hand, does it just right, meaning adds this extra new line.

**Comment by abo-abo** [comment]
Thanks, you can also customize `org-download-link-format` further.

**Comment by michaelsjackson** [comment]
Wow, that was a turbofast addition, thanks 1000 times, small difference, but now each time I can smile, as saving me those steps.
