### ISSUE TITLE
How to setup org-download with mac os

### ISSUE THREAD

**Issue by shrysr** [abo-abo/org-download#95]
I'm having trouble getting org-download to work with my Mac OS and request help. I am trying to setup  windowed screenshots (using screencapture) saved to the ./img folder relative to the org file that is open, and also inserted at point in the org file. I would rather specify the name of the screenshot file, or atleast have them saved with unique names automatically. 

Errors: 
1. When I use only screencapture : no file specified
2. When I use screencapture -c -i  : The file is saved to memory but cannot be yanked at point. 

Additional errors faced with (2) : 
```
screencapture: no file specified
helm-M-x: Bad url: ./img/tmp.png  
```

My configuration is as follows: 
``` 
(use-package org-download
  :ensure t 
  :config
  (require 'org-download)
  ;; Drag and drop to Dired
  (add-hook 'dired-mode-hook 'org-download-enable)
  (setq org-download-method 'directory)
  (setq-default org-download-image-dir "./img")
  (setq org-download-screenshot-method "screencapture -i")
  (setq org-download-screenshot-file "./img/tmp.png")
  )

**Comment by abo-abo** [comment]
Sorry, no idea. I don't use OSX. Maybe someone else can help.

**Comment by ephsmith** [comment]
The following has worked well for me:

`(org-download-screenshot-method "screencapture -i %s")`

**Comment by elsatch** [comment]
@shrysr did you manage to get it working? I agree with proposed solution by @ephsmith. You need to pass the string as a parameter to screencapture. I have the following lines on my .emacs:

 '(org-download-edit-cmd "open -n -a Preview %s")
 '(org-download-screenshot-file
   "/var/folders/sm/qn4tzvwx4731vj2djq1hsh9c0000gn/T/screenshot.png")
 '(org-download-screenshot-method "screencapture -io %s")

I assume that the screenshot-file was created randomly :)

Regarding the suggestion to ask for the filename to have unique names, right now org-download appends the date by default so no files should have the same name. Exploring the source, you can rename files using the functions org-download-rename-last-file and org-download-rename-at-point.

I think it could be very interesting for the org-download-screenshot to have an interactive option, that sets the org-download-screenshot-file from the mini buffer before launching the actual org-download-screenshot-method. 

My elisp-fu is not ready for such changes yet!

**Comment by shrysr** [comment]
Apologise for the delayed response @elsatch . I just tried again. In fact, all I have now is (org-download-screenshot-method "screencapture -i %s") as mentioned by @ephsmith and it works. FWIW, I've been using the drag and drop and org-download-yank with great pleasure.

**Comment by shrysr** [comment]
I'll close the issue as it does not seem to be an issue any more :)
